---

# Ejercicios NumPy

## Machine Learning para la industria 2019

---

#### Importa NumPy

#### Crea un arreglo  de 5 ceros

In [2]:
#Escribe tu respuesta aquí

array([0., 0., 0., 0., 0.])

#### Crea un arreglo de 5 unos

In [4]:
#Escribe tu respuesta aquí

array([1., 1., 1., 1., 1.])

#### Crea un arreglo de 5 ochos

In [8]:
#Escribe tu respuesta aquí

array([8., 8., 8., 8., 8.])

#### Crea un arreglo de enteros del 50 al 99

In [10]:
#Escribe tu respuesta aquí

array([50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66,
       67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83,
       84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

#### Reajusta el arreglo anterior para que tenga 5 filas

In [13]:
#Escribe tu respuesta aquí

array([[50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

#### Crea un arreglo de números pares de 50 a 100

In [12]:
#Escribe tu respuesta aquí

array([ 50,  52,  54,  56,  58,  60,  62,  64,  66,  68,  70,  72,  74,
        76,  78,  80,  82,  84,  86,  88,  90,  92,  94,  96,  98, 100])

#### Crea una matriz de 5x5 con valores del 0 al 24

In [24]:
#Escribe tu respuesta aquí

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

#### Crea una matriz identidad de 5x5

In [28]:
#Escribe tu respuesta aquí

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

#### Genera un número aleatorio con NumPy en el intervalo [0,1)

array([0.88936486])

#### Genera un arreglo de 10 números aleatorios tomados de una distribución normal estándar

In [30]:
#Escribe tu respuesta aquí

array([ 0.54779416, -0.08345511, -1.83663454, -0.0208563 , -0.15731701,
        0.14671886,  0.57329982,  0.3018676 , -1.6511817 , -1.94402184])

#### Crea la siguiente matriz:

In [36]:
#Escribe tu respuesta aquí

array([[0.01, 0.02, 0.03, 0.04, 0.05, 0.06, 0.07, 0.08, 0.09, 0.1 ],
       [0.11, 0.12, 0.13, 0.14, 0.15, 0.16, 0.17, 0.18, 0.19, 0.2 ],
       [0.21, 0.22, 0.23, 0.24, 0.25, 0.26, 0.27, 0.28, 0.29, 0.3 ],
       [0.31, 0.32, 0.33, 0.34, 0.35, 0.36, 0.37, 0.38, 0.39, 0.4 ],
       [0.41, 0.42, 0.43, 0.44, 0.45, 0.46, 0.47, 0.48, 0.49, 0.5 ],
       [0.51, 0.52, 0.53, 0.54, 0.55, 0.56, 0.57, 0.58, 0.59, 0.6 ],
       [0.61, 0.62, 0.63, 0.64, 0.65, 0.66, 0.67, 0.68, 0.69, 0.7 ],
       [0.71, 0.72, 0.73, 0.74, 0.75, 0.76, 0.77, 0.78, 0.79, 0.8 ],
       [0.81, 0.82, 0.83, 0.84, 0.85, 0.86, 0.87, 0.88, 0.89, 0.9 ],
       [0.91, 0.92, 0.93, 0.94, 0.95, 0.96, 0.97, 0.98, 0.99, 1.  ]])

#### Crea un arreglo de 10 puntos en el intervalo [1,5] separados a igual distancia entre ellos

In [41]:
#Escribe tu respuesta aquí

array([1.        , 1.44444444, 1.88888889, 2.33333333, 2.77777778,
       3.22222222, 3.66666667, 4.11111111, 4.55555556, 5.        ])

## Selección e indexación en NumPy

Dada la siguiente matriz, escribe el código necesario para obtener las selecciones que se te piden

In [6]:
mat = np.arange(1,26).reshape(5,5)
mat

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [39]:
#Escribe tu respuesta aquí

array([[13, 14, 15],
       [18, 19, 20],
       [23, 24, 25]])

In [45]:
#Escribe tu respuesta aquí

18

In [54]:
#Escribe tu respuesta aquí ¡Ojo!

array([[ 3],
       [ 8],
       [13]])

In [59]:
#Escribe tu respuesta aquí ¡Ojo!

array([21, 22, 23, 24, 25])

In [8]:
#Escribe tu respuesta aquí

array([[11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

### Práctica con funciones matemáticas

#### Suma todos los elementos de la matriz

In [64]:
#Escribe tu respuesta aquí

325

#### Obtén el promedio de los valores de la matriz

In [69]:
#Escribe tu respuesta aquí

13.0

#### Obtén la suma de las columnas de la matriz

In [71]:
#Escribe tu respuesta aquí

array([55, 60, 65, 70, 75])

#### Obtén la suma de las filas de la matriz

In [72]:
#Escribe tu respuesta aquí

array([ 15,  40,  65,  90, 115])